---
title: "formatOutputs"
author: "Daniel Mendelson"
date: "28/03/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(glue)
library(tidyr)
library(stringr)

```

```{r corFormat, echo=FALSE}
date <- str_c(format(Sys.time(), "%m"), "_", format(Sys.time(), "%d"), "_", format(Sys.time(), "%Y")) # set todays date for easier output filenaming  

listOfCovars <- c("demo_sex_t0Male","smoke_currently0_t0Yes","smoke_currently0_t0Yes","demo_ethnicity_t0White","exercise_IPAQActivityGroup_t0low","exercise_IPAQActivityGroup_t0moderate","ses_townsend_t0_z","demo_age_assess0_t0_z","demo_daysBtwAssess_z","weight_waistToHip_mean02_z","sleep_duration_mean02_z")

list_covarAllModels <- list() # this will store all dataframes with covariate information

filePath <- "/home/doodlefish/Documents/Research/LepageLab/immunologyAndSz/Analysis/immunoCognition-new/Outputs/Correl-WithC"
files <- c("UKBB_Anal_cor_cog_digsub_cor_t2_z_05_05_2022","UKBB_Anal_cor_cog_digsub_numAttempted_t2_z_05_05_2022","UKBB_Anal_cor_cog_fluidIntel_QsAttempted_t2_z_05_05_2022","UKBB_Anal_cor_cog_fluidIntel_score_t2_z_05_05_2022","UKBB_Anal_cor_cog_matrix_cor_t2_z_05_05_2022","UKBB_Anal_cor_cog_matrix_numViewed_t2_z_05_05_2022","UKBB_Anal_cor_cog_numMem_maxDigitRemem_t2_z_05_05_2022","UKBB_Anal_cor_cog_prospMem_timeDelay_t2_z_05_05_2022","UKBB_Anal_cor_cog_reactiontime_mean_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_alphanumDuration_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_alphanumErrors_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_numericDuration_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_numericErrors_t2_z_05_05_2022","UKBB_Anal_cor_cog_tower_cor_t2_z_05_05_2022")
catFile <- c("UKBB_Anal_cor_cog_prospMem_result_t2_05_05_2022")

corFormat(depVar = "crp_log_z", modelName = "cor_C", outputPrefix = "UKBB_cor_anal_crpCog_C", filePath = "/home/doodlefish/Documents/Research/LepageLab/immunologyAndSz/Analysis/immunoCognition-new/Outputs/Correl-WithC", listOfCovars = listOfCovars, files = files)

# bewlow function is broken
corFormat <- function(modelName, filePath, files, depVar, listOfCovars, outputPrefix){  
  df_main <- matrix(ncol = 13, dimnames = list(c(), c("model Name", "indep var", "dep var", "parameter estimate", "SE", "t", "p", "R^2", "R^2adj", "F", "df1", "df2", "p")))
  df_covarForModel <- matrix(ncol = length(listOfCovars)+2)
  df_covarForModel_tmp <- c()
  
  for(file in files){
    specificFilePath <- glue("{filePath}/{file}.txt")
    fileObj <- readLines(specificFilePath)
    
    lmExpression <- grep("~", fileObj, value = TRUE) # from this line, extract analysis name
    lmExpression <- unlist(strsplit(lmExpression, "\\s+"))
    indepVar <- lmExpression[which(lmExpression == "~")-1] # n.b. indep var of this model may not be indep var of mediation analysis
    name <- glue("{modelName}_{indepVar}")
    cat(name)
    depVarValues <- grep(depVar, fileObj, value = TRUE)[2]
    depVarValues <- unlist(strsplit(depVarValues, "\\s+"))
    
    if(TRUE %in% grepl("<", depVarValues)){
      pAndSymbol <- glue("{depVarValues[[5]]}{depVarValues[[6]]}")
      depVarValuesNoSigChar <- c(depVarValues[1:4], pAndSymbol)
    } else {
      depVarValuesNoSigChar <- depVarValues[1:5]
    }
    # cat(paste(name, depVarValuesNoSigChar, sep = "\n\t"))
  
    effectSizes <- grep("Multiple R-squared",fileObj, value = TRUE)
    effectSizes <- unlist(strsplit(effectSizes, "\\s+"))
    R2 <- substr(effectSizes[3], 1, nchar(effectSizes[3])-1)
    R2adj <- effectSizes[6]
    
    FTest <- grep("F-statistic",fileObj, value = TRUE)
    FTest <- unlist(strsplit(FTest, "\\s+"))
    FStat <- FTest[2]
    df1 <- FTest[4]
    df2 <- FTest[6]
    p <- FTest[which(FTest == grep("p-value",FTest, value = TRUE)):length(FTest)]
    
    if(TRUE %in% grepl("<", p)){
      p <- glue("{FTest[[9]]}{FTest[[10]]}")
      # p <- paste(FTest[[9]], FTest[[10]], sep = "")
    } else {
      p <- FTest[which(FTest == grep("p-value",FTest, value = TRUE))+1]
    }
    
    # if(listOfCovars[1] != ""){
    #   for(covar in listOfCovars){
    #     
    #     covarValues <- grep(covar, fileObj, value = TRUE)
    #     if(is.null(covarValues) == F){
    #       if(length(covarValues) == 2){
    #         covarValues <- covarValues[2]
    #       }
    #       indexNumBegin <- length(unlist(strsplit(covar, "\\s+")))
    #       covarValues <- unlist(strsplit(covarValues, "\\s+"))
    #   
    #       indexOfFirstNum <- indexNumBegin + 1
    #       indexOfLastNum <- indexNumBegin + 4
    #       
    #       if(TRUE %in% grepl("<", covarValues)){
    #         indexPreP <- indexOfLastNum - 1
    #         covarValues <- c(covar, covarValues[indexOfFirstNum : indexPreP], glue("{covarValues[[indexOfLastNum]]}{covarValues[[indexOfLastNum+1]]}"))
    #       # p <- paste(FTest[[9]], FTest[[10]], sep = "")
    #       } else {
    #         covarValues <- c(covar, covarValues[indexOfFirstNum:indexOfLastNum])
    #       }
    #     } else{
    #       covarValues <- rep("Error, missing data for covariates.", 5)
    #     }
    #     df_covarForModel_tmp <- cbind(df_covarForModel, covarValues)
    #   }
    #   name <- glue("{name}_C")
    #   if(sum(is.na(df_covarForModel_tmp[,1])) == nrow(df_covarForModel_tmp)){
    #      df_covarForModel_tmp <-  df_covarForModel_tmp[,-1]
    #   }
    #   dimnames(df_covarForModel) <- list(c(), listOfCovars)
    #   df_covarForModel <- df_covarForModel_tmp
    #   df_covarForModel <- cbind("modelName" = name, "statistic" = c("parameter estimate", "SE", "t", "p"), df_covarForModel_tmp)
    #   if(nrow(df_covarForModel) == 1){
    #     df_covarForModel <- rbind(df_covarForModel[-1,], df_covarForModel_tmp)
    #   } else {
    #     df_covarForModel <- rbind(df_covarForModel, df_covarForModel_tmp)
    #   }
    #   df_covarForModel <- c()
    #   write.csv(df_covarForModel, file = glue("{outputPrefix}_CovarWeights_{date}.csv"))
    # } else {
    #   name <- glue("{name}_noC")
    # }
    
    df_mainRow <- c(name, indepVar, depVarValuesNoSigChar, R2, R2adj, FStat, df1, df2, p)  # "Model name", "indep var", "dep var", "parameter estimate", "SE", "t", "p", "R^2", "R^2adj", "F", "df1", "df2", "p"
    df_main <- rbind(df_main, " " = df_mainRow)
  }

  df_main <- df_main[-1,]
  write.csv(df_main, file = glue("{outputPrefix}_CRPWeights_{date}.csv"))
} # 'modelName' - name of model for labelling output rows (usually 'cor' or 'med'), 'filePath' - path to folder housing files, 'files' - name of files (without extensions), 'depVar' - dependent variable (usually CRP_log_z), 'listOfCovars' - list of covariate variable names as listed in LM output (include level of contrast for categorical variables). If no covars, define as '""', 'outputPrefix' - string indicating the prefix for the output file. Note, independent variable is assumed to be the variable beginning with "cog_"

```

# Correl analyses
```{r formatOutputs, echo=FALSE}
# listOfFiles <- c("UKBB_Anal_cor_revC_cog_digsub_cor_t2_z_03_26_2022","UKBB_Anal_cor_revC_cog_fluidIntel_QsAttempted_t2_z_03_26_2022") # a list of all file names

# Correlational analyses -----
listOfCovars <- c("demo_sex_t0Male","smoke_currently0_t0Yes","smoke_currently0_t0Yes","demo_ethnicity_t0White","exercise_IPAQActivityGroup_t0low","exercise_IPAQActivityGroup_t0moderate","ses_townsend_t0_z","demo_age_assess0_t0_z","demo_daysBtwAssess_z","weight_waistToHip_mean02_z","sleep_duration_mean02_z")

corFormat(depVar = "crp_log_z", modelName = "cor_revC", outputPrefix = "UKBB_cor_anal_crpCog_revC", filePath = "/home/doodlefish/Documents/Research/LepageLab/immunologyAndSz/Analysis/immunoCognition-new/Outputs/CorAnalyses/NoC/04_01_2022", listOfCovars = listOfCovars, files = list("UKBB_Anal_cor_noC_cog_PC_1_z_04_01_2022","UKBB_Anal_cor_noC_cog_PC_2_z_04_01_2022","UKBB_Anal_cor_noC_cog_PC_3_z_04_01_2022"))

corFormat(depVar = "crp_log_z", modelName = "cor_noC", outputPrefix = "UKBB_cor_anal_crpCog_noC", filePath = "/home/doodlefish/Documents/Research/LepageLab/immunologyAndSz/Analysis/immunoCognition-new/Outputs/CorAnalyses/NoC", listOfCovars = "", files = list("UKBB_Anal_cor_cog_digsub_cor_t2_z_05_05_2022","UKBB_Anal_cor_cog_digsub_numAttempted_t2_z_05_05_2022","UKBB_Anal_cor_cog_fluidIntel_QsAttempted_t2_z_05_05_2022","UKBB_Anal_cor_cog_fluidIntel_score_t2_z_05_05_2022","UKBB_Anal_cor_cog_matrix_cor_t2_z_05_05_2022","UKBB_Anal_cor_cog_matrix_numViewed_t2_z_05_05_2022","UKBB_Anal_cor_cog_numMem_maxDigitRemem_t2_z_05_05_2022","UKBB_Anal_cor_cog_prospMem_result_t2_05_05_2022","UKBB_Anal_cor_cog_prospMem_timeDelay_t2_z_05_05_2022","UKBB_Anal_cor_cog_reactiontime_mean_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_alphanumDuration_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_alphanumErrors_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_numericDuration_t2_z_05_05_2022","UKBB_Anal_cor_cog_TMT_numericErrors_t2_z_05_05_2022","UKBB_Anal_cor_cog_tower_cor_t2_z_05_05_2022"))

```

# Mediation analyses
```{r RMediationFunction, echo=FALSE}

listOfMediators <- c("brain_vol_brainSegNoVent_t2_z","brain_vol_hippocamp_L_t2_z","brain_vol_hippocamp_R_t2_z") # list of mediator variable names
df_covarForModel <- matrix(nrow = 5)
df_covarForModel <- matrix(ncol = length(listOfCovars)+2)
list_covarAllModels <- list() # this will store all dataframes with covariate information
# initialize counters
file <- ""
covar <- ""
date <- str_c(format(Sys.time(), "%m"), "_", format(Sys.time(), "%d"), "_", format(Sys.time(), "%Y")) # set todays date for easier output filenaming

# without covars
filePath = "/home/doodlefish/Documents/Research/LepageLab/immunologyAndSz/Analysis/immunoCognition-new/Outputs/MedAnalyses/noC"
files = c("UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_digsub_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_fluidIntel_QsAttempted_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_fluidIntel_score_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_matrix_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_numMem_maxDigitRemem_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_PC_1_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_PC_2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_PC_3_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_prospMem_timeDelay_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_reactiontime_mean_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_TMT_alphanumDuration_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_TMT_alphanumErrors_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_TMT_numericDuration_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_TMT_numericErrors_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_brainSegNoVent_t2_z_cog_tower_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_digsub_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_fluidIntel_QsAttempted_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_fluidIntel_score_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_matrix_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_numMem_maxDigitRemem_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_PC_1_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_PC_2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_PC_3_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_prospMem_timeDelay_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_reactiontime_mean_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_TMT_alphanumDuration_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_TMT_alphanumErrors_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_TMT_numericDuration_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_TMT_numericErrors_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_L_t2_z_cog_tower_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_digsub_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_fluidIntel_QsAttempted_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_fluidIntel_score_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_matrix_cor_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_numMem_maxDigitRemem_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_PC_1_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_PC_2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_PC_3_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_prospMem_timeDelay_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_reactiontime_mean_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_TMT_alphanumDuration_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_TMT_alphanumErrors_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_TMT_numericDuration_t2_z_03_26_2022","UKBB_Anal_med_noC_brain_vol_hippocamp_R_t2_z_cog_TMT_numericErrors_t2_z_03_26_2022")

# with covars
filePath <- "/home/doodlefish/Documents/Research/LepageLab/immunologyAndSz/Analysis/immunoCognition-new/Outputs/MedAnalyses/C/revC_04_01_2022_95CI"
files <- c("UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_digsub_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_fluidIntel_QsAttempted_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_prospMem_timeDelay_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_fluidIntel_score_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_reactiontime_mean_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_matrix_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_TMT_alphanumDuration_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_numMem_maxDigitRemem_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_TMT_alphanumErrors_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_PC_1_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_TMT_numericDuration_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_PC_2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_TMT_numericErrors_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_PC_3_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_tower_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_digsub_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_prospMem_timeDelay_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_fluidIntel_QsAttempted_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_reactiontime_mean_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_fluidIntel_score_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_TMT_alphanumDuration_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_matrix_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_TMT_alphanumErrors_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_numMem_maxDigitRemem_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_TMT_numericDuration_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_PC_1_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_TMT_numericErrors_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_PC_2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_brainSegNoVent_t2_z_cog_tower_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_PC_3_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_digsub_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_fluidIntel_QsAttempted_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_prospMem_timeDelay_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_fluidIntel_score_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_reactiontime_mean_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_matrix_cor_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_TMT_alphanumDuration_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_numMem_maxDigitRemem_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_TMT_alphanumErrors_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_PC_1_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_TMT_numericDuration_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_PC_2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_TMT_numericErrors_t2_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_L_t2_z_cog_PC_3_z_04_01_2022","UKBB_Anal_med_revC_brain_vol_hippocamp_R_t2_z_cog_tower_cor_t2_z_04_01_2022")

listOfCovars <- ""

# filePath = "/home/doodlefish/Documents/Research/LepageLab/immunologyAndSz/Analysis/immunoCognition-new/Outputs/MedAnalyses/C"
# files = "UKBB_Anal_med_C_brain_vol_brainSegNoVent_t2_z_cog_PC_3_z_03_26_2022"
# covars <- c("brain_vol_brainSegNoVent_t2_z","demo_sex_t0Male","demo_ethnicity_t0East Asian","demo_ethnicity_t0Mixed","demo_ethnicity_t0Other ethnic group", "demo_ethnicity_t0South Asian", "demo_ethnicity_t0White","demo_age_assess0_t0","demo_daysBtwAssess_z", "hand_t0LH","hand_t0Not","hand_t0RH","brain_headScale_t2","cog_hourCompleted")

variables <- c()
values <- c()
valueList <- c()
df_main <- matrix(ncol = 38, dimnames = list(c(), c("modelName", "X", "M", "Y", "IndEff_est", "IndEff_SE", "IndEff_95%CI-Lo","IndEff_95%CI-Hi","DirEff_b", "DirEff_SE", "DirEff_X_t", "DirEff_X_p", "DirEff_model_R^2", "DirEff_model_R^2adj", "DirEff_model_F", "DirEff_model_df1", "DirEff_model_df2", "DirEff_model_p", "aPath_b", "aPath_SE", "aPath_X_t", "aPath_X_p", "aPath_model_R^2", "aPath_model_R^2adj", "aPath_model_F", "aPath_model_df1", "aPath_model_df2", "aPath_model_p", "bPath_b", "bPath_SE", "bPath_X_t", "bPath_X_p", "bPath_model_R^2", "bPath_model_R^2adj", "bPath_model_F", "bPath_model_df1", "bPath_model_df2", "bPath_model_p")))
name <- "med_revC"
bPathRows <- c()
  
for(file in files){
  specificFilePath <- glue("{filePath}/{file}.txt")
  fileObj <- readLines(specificFilePath)
  
  splits <- grep("~", fileObj)
  split1 <- splits[2]-2
  split2 <- splits[3]-2
  medOutput <- grep("Mediated Effect", fileObj)
  
  text_directEffect <- fileObj[2:split1]
  text_aPath <- fileObj[(split1+1):split2]
  text_bPath <- fileObj[(split2+1):(medOutput-1)]
  text_mediatedEffect <- fileObj[medOutput:length(fileObj)]
  models <- list(text_directEffect, text_aPath, text_bPath)
  
  for(i in 1:(length(models))){ # iterate through all three models
    # Find name of mediator, indep var
    sectionText <- unlist(models[i])
    lmExpression <- grep("~", sectionText, value = TRUE) # from this line, extract analysis name
    lmExpression <- unlist(strsplit(lmExpression, "\\s+"))
    indepVar <- lmExpression[which(lmExpression == "~")-1] # n.b. indep var of this model may not be indep var of mediation analysis
    depVar <- lmExpression[which(lmExpression == "~")+1]
    
    depVarValues <- grep(depVar, sectionText, value = TRUE)
    if(length(depVarValues) == 2){
      depVarValues <- depVarValues[2]
    }
    
    depVarValues <- unlist(strsplit(depVarValues, "\\s+"))
    
    if(TRUE %in% grepl("<", depVarValues) && nchar(depVarValues[grep("<",depVarValues)]) == 1){
      pAndSymbol <- glue("{depVarValues[[5]]}{depVarValues[[6]]}")
      depVarValuesNoSigChar <- c(depVarValues[2:4], pAndSymbol)
    } else {
      depVarValuesNoSigChar <- depVarValues[2:5]
    }
    
    effectSizes <- grep("Multiple R-squared",sectionText, value = TRUE)
    effectSizes <- unlist(strsplit(effectSizes, "\\s+"))
    R2 <- substr(effectSizes[3], 1, nchar(effectSizes[3])-1)
    R2adj <- effectSizes[6]
    
    FTest <- grep("F-statistic",sectionText, value = TRUE)
    FTest <- unlist(strsplit(FTest, "\\s+"))
    FStat <- FTest[2]
    df1 <- FTest[4]
    df2 <- FTest[6]
    
    p <- FTest[which(FTest == grep("p-value", FTest, value = TRUE)):length(FTest)]
    if(TRUE %in% grepl("<", p) && nchar(p[grep("<",p)]) == 1){
      p <- glue("{FTest[[9]]}{FTest[[10]]}")
      # p <- paste(FTest[[9]], FTest[[10]], sep = "")
    } else {
      p <- FTest[which(FTest == grep("p-value",FTest, value = TRUE))+1]
    }
    
    ########################################################33
    # bPathRows <- grep("b path", sectionText, value = TRUE)
    # if(is.null(bPathRows) == FALSE){ # extract med -> Y in b path model
    #   brainVarValues <- sectionText[starts_with("brain_", vars = sectionText)]
    #   for(i in length(brainVarValues)){
    #     splitRow <- strsplit(brainVarValues[i], "\\s+")
    #     for(j in splitRow){
    #       if(splitRow %in% listOfMediators == T){
    #         print("hi")
    #       }
    #     }
    #   }
    #   
    #   contains(brainVarValues, vars = listOfMediators)
    #   brainVarValues <- unlist(strsplit(brainVarValues, "\\s+"))
    #   if(TRUE %in% grepl("<", brainVarValues) && nchar(brainVarValues[grep("<", brainVarValues)]) == 1){
    #     pAndSymbol <- glue("{brainVarValues[[5]]}{brainVarValues[[6]]}")
    #     brainVarValuesNoSigChar <- c(brainVarValues[2:4], pAndSymbol)
    #   } else {
    #     brainVarValuesNoSigChar <- brainVarValues[2:5]
    #   }
    #   df_covarForModel <- cbind(df_covarForModel,  brainVarValuesNoSigChar)
    # }
    #####################################################################333

    # listOfCovars <- c(, )
    # if(listOfCovars[1] != ""){
    #   for(covar in listOfCovars){
    #   #   covarValues <- grep(covar, sectionText, value = TRUE)
    #   #   if(is.null(covarValues) == F){
    #   #     if(length(covarValues) == 2){
    #   #       covarValues <- covarValues[2]
    #   #     }
    #   #     indexNumBegin <- length(unlist(strsplit(covar, "\\s+")))
    #   #     covarValues <- unlist(strsplit(covarValues, "\\s+"))
    #   # 
    #   #     indexOfFirstNum <- indexNumBegin + 1
    #   #     indexOfLastNum <- indexNumBegin + 4
    #   #     
    #   #     if(TRUE %in% grepl("<", covarValues)){
    #   #       indexPreP <- indexOfLastNum - 1
    #   #       covarValues <- c(covar, covarValues[indexOfFirstNum : indexPreP], glue("{covarValues[[indexOfLastNum]]}{covarValues[[indexOfLastNum+1]]}"))
    #   #     # p <- paste(FTest[[9]], FTest[[10]], sep = "")
    #   #     } else {
    #   #       covarValues <- c(covar, covarValues[indexOfFirstNum:indexOfLastNum])
    #   #     }
    #   #   } else{
    #   #     covarValues <- rep("Error, missing data.", 5)
    #   #   }
    #   #   df_covarForModel <- cbind(df_covarForModel, covarValues)
    #   # }
    #   # name <- glue("{name}_C")
    #   # if(sum(is.na(df_covarForModel[,1])) == nrow(df_covarForModel)){
    #   #     df_covarForModel <-  df_covarForModel[,-1]
    #   # }
    #   # dimnames(df_covarForModel) <- list(c(), listOfCovars)
    #   # df_covarForModel_tmp <- df_covarForModel[-1,]
    #   # df_covarForModel_tmp <- cbind("modelName" = name, "statistic" = c("parameter estimate", "SE", "t", "p"), df_covarForModel_tmp)
    #   # if(nrow(df_covarForModel) == 1){
    #   #   df_covarForModel <- rbind(df_covarForModel[-1,], df_covarForModel_tmp)
    #   # } else {
    #   #   df_covarForModel <- rbind(df_covarForModel, df_covarForModel_tmp)
    #   # }
    #   # df_covarForModel <- c()
    #   # write.csv(df_covarForModel, file = glue("{outputPrefix}_CovarWeights_{date}.csv"))
    #   }
    # } else {
    #   # name <- glue("{name}_noC")
    # }
    variables <- append(variables, c(indepVar, depVar))
    values <- append(values, c(depVarValuesNoSigChar, R2, R2adj, FStat, df1, df2, p))
  }
  
  indepVar <- variables[2]
  medVar <- variables[3]
  depVar <- variables[1]
  vars <- c(indepVar, medVar, depVar)
  name <- glue("{name}_{medVar}_{depVar}")
  
  # Extract indirect effect
  sectionText <- text_mediatedEffect
  
  medEff_est <- grep("Estimate",sectionText, value = TRUE)
  medEff_est <- unlist(strsplit(medEff_est, "\\s+"))
  medEff_est <-  medEff_est[3]
  
  medEff_SE <- grep("SE",sectionText, value = TRUE)
  medEff_SE <- unlist(strsplit(medEff_SE, "\\s+"))
  medEff_SE <-  medEff_SE[3]
  
  medEff_95Low <- grep("95%CILow",sectionText, value = TRUE)
  medEff_95Low <- unlist(strsplit(medEff_95Low, "\\s+"))
  medEff_95Low <-  medEff_95Low[3]
  
  medEff_95Hi<- grep("95%CIHi",sectionText, value = TRUE)
  medEff_95Hi <- unlist(strsplit(medEff_95Hi, "\\s+"))
  medEff_95Hi <-  medEff_95Hi[3]
  
  indEff <- c(medEff_est, medEff_SE, medEff_95Low, medEff_95Hi)
  
  df_main <- rbind(df_main, c(name, vars, indEff, values)) # specify the indices of valueList to retain in main_df
  
  variables <- c()
  values <- c()
  name <- "med_noC"
}
as.data.frame(df_main)
df_main <- df_main[-1,]
write.csv(df_main, file = glue("UKBB_med_anal_results_CRPWeights_revC_{date}.csv"))
write.csv(df_main, file = glue("{outputPrefix}_CRPWeights_{date}.csv"))
```
