---
title: "immunoCognition_Analyses"
author: "Daniel Mendelson"
date: "04/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(readxl)
```

# Biobank data
## Data Preperation
## Analysis

```{r biobank, echo=FALSE}

```

# Mizrahi
## Data Preperation & Baseline Description

```{r mizrahi, echo=FALSE}

# Import relevant data
#N.b. re: naming of dataframes: 'M' in "M_#...#" is for Prof Romina Mizrahi.
M_primary <- read.csv("data/merged_demographics_romina.csv")
M_MissingCytokinesA <- readxl::read_excel("data/Cytokines_LC.xlsx") # file with missing data from the primary import
M_MissingCytokinesB <- readxl::read_excel("data/1636401400878_Cytokines_LC.xlsx") # file with missing data from the primary import
M_RBANS <- read.csv("data/RBANS.csv") # file with RBANS total scores
# M_RBANS <- M_RBANS[1:183,] # all rows after 183 are empty observations. !! There is certainly a better way of doing this. I.e. remove empty rows. perhaps dplyr::across !!
# M_RBANS
M_RBANS_clean <- M_RBANS %>% drop_na # removes rows with any missing values

M_primary_RBANS <- full_join(M_primary, M_RBANS_clean) # Add the RBANS results to the reference dataframe
# M_primary_RBANS[order(M_primary_RBANS$RBANS.Total.Score),c(4,73)]
# M_primary_RBANS[is.na(M_primary_RBANS$RBANS.Total.Score),]

M_primary_RBANS_A <- full_join(M_primary_RBANS, M_MissingCytokinesA) # Add the RBANS results to the reference dataframe
# M_primary_RBANS_A[order(M_primary_RBANS_A$FEPPA.IDs),]

M_primary_RBANS_AB <- full_join(M_primary_RBANS_A, M_MissingCytokinesB) # Add the RBANS results to the reference dataframe
# M_primary_RBANS_AB[order(M_primary_RBANS_B$FEPPA.IDs),]

# complete.cases(M_primary_RBANS)
# typeof(M_primary_RBANS_AB$Group)
# typeof(M_primary_RBANS_AB$Groups)

colnames(M_primary_RBANS_AB)
# table(M_primary_RBANS_AB$Group)
# table(M_primary_RBANS_AB$Groups)
# Summarize by condition

M_primary_RBANS_AB %>%
    group_by(Groups) %>%
    dplyr::summarise(n = n(), AgeMean = mean(Age, na.rm=TRUE), AgeSD = sd(Age, na.rm=TRUE))

M_primary_RBANS_AB %>%
    group_by(Group) %>%
    dplyr::summarise(n = n(), AgeMean = mean(Age, na.rm=TRUE), AgeSD = sd(Age, na.rm=TRUE))

```
## Analysis

